hello: vec_sample.hpp vec_sample_wrap.cpp
	g++ -shared -o libvec_sample.so -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -fPIC vec_sample.hpp vec_sample_wrap.cpp
